name = "nuxt-theme-podcast"
pages_build_output_dir = "playground/dist"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-10-24"

[vars]
# Optional: override the feed URL from app.config.ts
# FEED_URL = "https://changelog.com/podcast/feed"
